GET http://localhost:3000/my_name.json
###
GET http://localhost:3000/first_letter.json?name=Abe
###
GET http://localhost:3000/guess_number.json?number=10
###
GET http://localhost:3000/addition/2/3
###
GET http://localhost:3000/guess_the_number/12
###
POST http://localhost:3000/guess_a_number
content-type: application/json

{
  "number": "20"
}
###
POST http://localhost:3000/login
content-type: application/json

{
  "username": "hugh",
  "password": "swordfish"
}